import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Ganti import Geist dengan Inter
import "./globals.css";

// Konfigurasi font Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Gunakan className dari font Inter */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}